############################
## Author
############################

author:
  name: Elisa Ferrari
  image: author.png
  greeting: "Driven by data. Focused on lives."
  #icon: ":wave:"

############################
## Links
############################

links:
  - linkedin: https://www.linkedin.com/in/elisa-ferrari-data-analyst/
  - github: https://github.com/elisa-qb
  - x-twitter: https://x.com/ElisaFerra2119
  # - mastodon: 
  # - instagram: 
  # - reddit: 
  - telegram: https://t.me/Elisa_Ferrari 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  - email: mailto:elisa.ferrari@quantabrain.ai 
  - website: https://quantabrain.org 
  # - link: https://quantabrain.org
  # - discord: 
  # - orcid: 
  # - slack: 
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: website
description: "Site build with Qubt & Hugo"
images:
  - thumbnail.png
